name: Java CI

on:
  push:
    branches: [ '*' ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        javaver: [11, 16, 17]
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.javaver }}
        distribution: 'temurin'

    - name: Set up Ant and Ivy
      run: |
        ANT_LIB=/usr/share/ant/lib
        wget https://repo1.maven.org/maven2/org/apache/ivy/ivy/2.5.0/ivy-2.5.0.jar -P ${ANT_LIB}
        java -version
        ant -version

    - name: Resolve dependencies
      run: ant setup

    - name: Build and CI with Ant
      run: ant -version #ci


